- name: 创建etcd相关目录
  file: 
    name: "{{ item }}"
    state: directory
  with_items:
  - /etc/kubernetes/pki/etcd
  - "{{ etcd.dataDir }}"
  - /etc/etcd

- set_fact:
    clusterName: "{{ ansible_hostname }}"
  when: clusterName is undefined


- name: 分发etcd二进制文件
  copy:
    src: "{{ item }}"
    dest: "{{ item }}"
    mode: u+x
  with_items:
    - /usr/local/bin/etcd
    - /usr/local/bin/etcdctl
  
- name: 分发etcd证书
  copy: src={{ item }} dest=/etc/kubernetes/pki/etcd/
  with_fileglob:
    - '/etc/kubernetes/pki/etcd/*'

- name: 分发etcd配置文件和systemd文件
  template: src=templates/{{ item.src }} dest={{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}
  with_items:
  - { src: 'etcd.config.yml.j2', dest: '/etc/etcd' }
  - { src: 'etcd.service.j2', dest: '/usr/lib/systemd/system' }

- name: 渲染etcd备份脚本
  template: src={{ item.src }} dest={{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}
  with_items:
  - { src: 'etcd_cron.sh.j2', dest: '{{ inventory_dir }}/'}
  connection: local
  run_once: true

- name: 启动etcd并设置成开机启动
  systemd:
    name: etcd 
    state: restarted 
    enabled: yes 
    daemon_reload: yes
  when: not ( redo | default(false) )
